version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - kalshi-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - KALSHI_API_KEY=${KALSHI_API_KEY}
      - KALSHI_PRIVATE_KEY_PATH=/app/keys/private_key.pem
      - DATABASE_PATH=/app/data/kalshi_data.db
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    volumes:
      - ./backend/keys:/app/keys:ro
      - kalshi-data:/app/data
    depends_on:
      - redis
    networks:
      - kalshi-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kalshi-network

volumes:
  kalshi-data:
  redis-data:

networks:
  kalshi-network:
    driver: bridge